### ISSUE TITLE
紹介するゲームについて各自で決定

### ISSUE THREAD

**Issue by kamesaniniad** [kamesaniniad/team-project#1]
何を紹介するか、どんな感じにするか決めといてくれるとたすかります

**Comment by s1f102101918** [comment]
第一候補：第五人格
第二候補：ぷよクエ

**Comment by s1F102101008** [comment]
第一候補：プロセカ
第二候補：決戦平安京
第三候補：sky

2021年6月11日(金) 18:07 スタプラ ***@***.***>:
