### ISSUE TITLE
トップページのデザイン

### ISSUE THREAD

**Issue by kamesaniniad** [kamesaniniad/team-project#2]
トップページのデザインについて大まかでもなんでもいいので提案する場所
文字でも画像でもOK

**Comment by s1f102101918** [comment]
ざっくり配置でHTMLとCSS書いてコミットしといたので確認しておいてもらえると助かる。

**Comment by kamesaniniad** [comment]
めっちゃいいですねこれ
あとはこれを肉付けしてく感じでいきましょう
