### ISSUE TITLE
それぞれの紹介ページのデザイン

### ISSUE THREAD

**Issue by kamesaniniad** [kamesaniniad/team-project#3]
それぞれの紹介ページのデザインについて提案する場所

**Comment by kamesaniniad** [comment]
内容は全員が好きなように作ればいいとおもうんですけど、デザインは統一したほうが良いと思うのでCSSは誰かが作ったやつを全員で共有する形にしたほうがいいかなと思います

**Comment by s1f102101918** [comment]
今のとこ特に自分は何も考えてないので、個人ページはこんな感じのレイアウトでやりたいとかの希望が上がってくると考えやすいなって状態です。

**Comment by s1F102101008** [comment]
あっっっここに連絡来てたのか…気付かなかったごめんんん

2021年6月11日(金) 22:22 スタプラ ***@***.***>:

**Comment by kamesaniniad** [comment]
メールでも通知くるけどGitHubのアプリ入れるのもオススメ
アプリから諸々の通知くるし
