### ISSUE TITLE
トップに戻るボタンの実装

### ISSUE THREAD

**Issue by kamesaniniad** [kamesaniniad/team-project#5]
ボタンをクリックするとページのトップに戻れるやつをつくる
参考：[コードのお手本がたくさんのってるサイト](https://codepen.io/)

**Comment by kamesaniniad** [comment]
スタプラさんおねがいします

**Comment by s1f102101918** [comment]
了解しました。

**Comment by s1f102101918** [comment]
仕組みがさっぱりわからなかったのでいい感じのをそのまま持ってきました。
皆の案を統合するときに組み込んでもらえればいいかなと思います。

**Comment by kamesaniniad** [comment]
ありがとう！確認しました！
