### ISSUE TITLE
ツイートボタンの実装

### ISSUE THREAD

**Issue by kamesaniniad** [kamesaniniad/team-project#7]
やっぱりWebページは共有できてこそナンボだと思うんですよ
押したらツイートできるボタンを作りましょう

**Comment by s1f102101918** [comment]
了解しました、テンプレ探しの旅に行ってまいります。
モチベが持てば土日中に…。

**Comment by s1f102101918** [comment]
stprsolo.htmlのサイドバー部分に実装しました。

**Comment by s1f102101918** [comment]
おまけで追従サイドバーを上記と同じ個所に実装しました。
